version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run: ./build.sh
      - store_artifacts:
          path: fullmon.tar.gz
workflows:
  version: 2
  build:
    jobs:
      - build
